version: '3.9'

services:
  frontend:
    container_name: react-app
    build: ./ComputexFrontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - frontend_network
  backend:
    container_name: django-app
    build: ./Computex
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - backend_network
      - frontend_network

  database:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=recipe

    volumes:
      - ddata:/var/lib/postgresql/data
    networks:
      - backend_network

volumes:
  ddata:


networks:
  frontend_network:
  backend_network:
